### ISSUE TITLE
RGI06 for Reg02- Western Canada and USA not reproducible from GLIMS data base

### ISSUE THREAD

**Issue by burnout-stephl** [GLIMS-RGI/glims_issue_tracker#8] opened 2021-08-23 13:29 UTC
Similar to region 7, RGI06 is not reproducible using data from GLIMS data base. While outlines are available from GLIMS, RGI06 is obviously made up using revised rock outcrops / ice free areas within glaciers. Especially submission-ID 614 is affected by this issue.
Glacier ID G235390E51067N (subm. 623) is missing in GLIMS, others too? 

![subm_614](https://user-images.githubusercontent.com/57042208/130455569-70299541-0e2e-456b-8218-126cf455b712.jpg)
fig.1: GLIMS data (subm_ID: 614, blue) over RGI06 (red). RGI06 shows outcrops not captured by GLIMS data.

![subm_623](https://user-images.githubusercontent.com/57042208/130455600-d2c4b8cd-1e21-467f-b48f-0089c4dcf52d.jpg)
fig.2: GLIMS data (subm_ID: 623, blue) over RGI06 (red). Glacier G235390E51067N missing in GLIMS.

**Comment by fmaussion** [comment] 2021-11-28 18:57
Update -  I can reproduce the issues with 623 (Bolch). Two large glaciers are missing from GLIMS, and some "polygons in polygons" are in GLIMS but not RGI, as well as some rock outcrops that are in RGI but not GLIMS. E.g.:

![image](https://user-images.githubusercontent.com/10050469/143781910-7721597f-fb2c-4697-a29a-cb3182b2e3f6.png)

![image](https://user-images.githubusercontent.com/10050469/143781952-6ad5ee4b-8eb7-453b-aff0-4c5bea9f7462.png)

The total area difference (once the two large glaciers are added) is 6km2, which is tolerable. To discuss.

**Comment by fmaussion** [comment] 2021-11-28 19:03
Update 614 (Andrew Fountain): the rock outcrops are missing from GLIMS, it's not due to our post-processing in RGI:

![image](https://user-images.githubusercontent.com/10050469/143782151-ecb5ebab-81cc-491e-92a1-80a9dd883b1e.png)

**Comment by fmaussion** [comment] 2021-12-01 17:21
One more update to summarize: 
- the issue of missing glaciers in Canada is solved now thanks to @bruceraup. These glaciers are now available in two additional submissions
- still, there is 6km2 difference in area between GLIMS and RGI for Tobias Bolch's inventory in Canada. This comes from differences in rock outcrops between the two datasets, which I am tempted to ignore (see examples above)
- and still, the Andrew Fountain dataset does not contain any Rock outcops in GLIMS, @bruceraup is working on that.

**Comment by fmaussion** [comment] 2021-12-02 16:51
Closed as of December 2. Thanks @bruceraup !

**Closed as completed by fmaussion** 2021-12-02 16:51 UTC
